/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => WordlePlugin
});
var import_obsidian2 = __toModule(require("obsidian"));

// src/view.ts
var import_obsidian = __toModule(require("obsidian"));
var WORDLE_VIEW_TYPE = "wordle-view";
var WordleView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
  }
  getViewType() {
    return WORDLE_VIEW_TYPE;
  }
  getDisplayText() {
    return "Wordle";
  }
  getIcon() {
    return "la:file-word-solid";
  }
  onOpen() {
    return __async(this, null, function* () {
      console.log("[Wordle]: Opening view.");
      const container = this.containerEl.children[1];
      container.id = "wordle-container";
      container.empty();
      const iframe = container.createEl("iframe");
      iframe.src = "https://www.nytimes.com/games/wordle/index.html";
      iframe.id = "wordle-iframe";
    });
  }
  onClose() {
    return __async(this, null, function* () {
      console.log("[Wordle]: Closing view.");
    });
  }
};

// src/main.ts
var WordlePlugin = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      console.log("[Wordle]: loaded plugin.");
      (0, import_obsidian2.addIcon)("la:file-word-solid", `<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="la" data-icon="file-word-solid" role="img" viewBox="0 0 32 32"><path fill="currentColor" d="M6 3v26h20V3zm2 2h16v22H8zm10 7v6.5c0 .215-.285.5-.5.5c-.043 0 .02.047-.063-.063c-.082-.109-.207-.386-.28-.687C17.006 17.652 17 17 17 17v-2h-2v4.5c0 .215-.285.5-.5.5c-.215 0-.5-.285-.5-.5V13h-4v2h2v4.5c0 1.383 1.117 2.5 2.5 2.5c.984 0 1.688-.645 2.094-1.469c.3.188.52.469.906.469c1.383 0 2.5-1.117 2.5-2.5V14h2v-2z" /></svg>`);
      this.registerView(WORDLE_VIEW_TYPE, (leaf) => new WordleView(leaf));
      this.activateView();
    });
  }
  onunload() {
    return __async(this, null, function* () {
      this.app.workspace.detachLeavesOfType(WORDLE_VIEW_TYPE);
      console.log("[Wordle]: unloaded plugin.");
    });
  }
  activateView() {
    this.app.workspace.onLayoutReady(() => __async(this, null, function* () {
      this.app.workspace.detachLeavesOfType(WORDLE_VIEW_TYPE);
      yield this.app.workspace.getRightLeaf(false).setViewState({
        type: WORDLE_VIEW_TYPE,
        active: true
      });
      this.app.workspace.revealLeaf(this.app.workspace.getLeavesOfType(WORDLE_VIEW_TYPE)[0]);
    }));
  }
};
